---
driver:
  name: vagrant
  vm_hostname: 'postfixadmin.local'
  network:
  - ["forwarded_port", {guest: 80, host: 8080, auto_correct: true}]
  - ["forwarded_port", {guest: 443, host: 8443, auto_correct: true}]

provisioner:
  require_chef_omnibus: true
  data_path: test/shared

platforms:
- name: ubuntu-10.04
  run_list: ["recipe[apt]"]
- name: ubuntu-12.04
  run_list: ["recipe[apt]"]
- name: ubuntu-14.04
  run_list: ["recipe[apt]"]
- name: debian-6.0.10
  run_list: ["recipe[apt]"]
- name: debian-7.8
  run_list: ["recipe[apt]"]
- name: centos-5.11
  run_list: ["recipe[selinux::disabled]"]
- name: centos-6.6
  run_list: ["recipe[selinux::disabled]"]
- name: fedora-20
  run_list: ["recipe[selinux::disabled]"]

suites:
- name: mysql
  run_list:
  - recipe[postfixadmin_test::default]
- name: postgresql
  excludes:
  # https://github.com/hw-cookbooks/postgresql/issues/249
  - ubuntu-10.04
  - ubuntu-12.04
  - debian-6.0.10
  - debian-7.8
  - fedora-20
  run_list:
  - recipe[postfixadmin_test::default]
  attributes:
    postfixadmin:
      database:
        type: postgresql
- name: nginx
  excludes:
  # a conflict between mysql and php-fpm packages
  - centos-5.11
  run_list:
  - recipe[postfixadmin_test]
  attributes:
    postfixadmin:
      web_server: nginx
- name: without-webserver
  excludes:
  # some dependency installs apache2
  - ubuntu-10.04
  - debian-6.0.10
  run_list:
  - recipe[postfixadmin_test]
  attributes:
    postfixadmin:
      web_server: false
- name: map_files
  run_list:
  - recipe[postfix-full]
  - recipe[postfixadmin_test::map_files]
- name: ssl
  excludes:
  # apache2::mod_ssl not compatible
  - centos-5.11
  run_list:
  - recipe[postfixadmin_test::default]
  attributes:
    postfixadmin:
      ssl: true
- name: ssl-port
  excludes:
  # apache2::mod_ssl not compatible
  - centos-5.11
  run_list:
  - recipe[postfixadmin_test::default]
  attributes:
    postfixadmin:
      port: 8443
      ssl: true
